version: '3.17'
services:
    database:
        image: postgres
        restart: always
        hostname: database
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=orotig
    server:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
            - database
        restart: unless-stopped
        ports:
            - "8080:8080"
