version: '3.17'
services:
    database:
        image: postgres:latest
        restart: always
        hostname: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=orotig
        volumes:
            - database_data:/pgdata

    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin

    server:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - database
        restart: unless-stopped
        ports:
            - "8080:8080"

volumes:
    database_data:
    pgadmin_data:
